const MutationTypes = {
  GET_OBJECT_LIST : 'GET_OBJECT_LIST',
  GET_OBJECT_BY_ID : 'GET_OBJECT_BY_ID',
  ADD_TO_CART : 'ADD_TO_CART',
  CLEAR_CART : 'CLEAR_CART',
  INIT_DETAIL : 'INIT_DETAIL',
  INIT_USER : 'INIT_USER',
  GET_USER_LIST : 'GET_USER_LIST',
  GET_USER_BY_ID : 'GET_USER_BY_ID',
  ADD_USER : 'ADD_USER',
  UPDATE_USER : 'UPDATE_USER',
  DELETE_USER : 'DELETE_USER',
}

const CommonTypes = {
  TOGGLE_LOADING: 'TOGGLE_LOADING'
}

const Modes = {
  INIT: 'INIT',
  EDIT: 'EDIT',
  READ: 'READ',
}

export {
  MutationTypes,
  CommonTypes,
  Modes,
}